Cadastro de usuario e parte do login
gabrielsanttana/rolling-tetris pull request #10
Opened 2020-12-15 23:46 UTC by ticollapse

2020-12-31 05:48 UTC, gabrielsanttana requested changes

2020-12-31 05:48 UTC, gabrielsanttana commented on src/services/api.php
> +
```suggestion
```

2020-12-31 19:49 UTC, gabrielsanttana requested changes

2020-12-31 19:49 UTC, gabrielsanttana commented on src/containers/Edit/index.php
> +        <label for="password">Deixe em branco para não mudar</label>
```suggestion
        <label for="passwordConfirmation">Deixe em branco para não mudar</label>
```

2021-01-01 04:16 UTC, gabrielsanttana requested changes

2021-01-01 04:16 UTC, gabrielsanttana commented on src/services/api.php
> +
```suggestion
```

2021-01-02 19:02 UTC, gabrielsanttana requested changes

2021-01-02 19:02 UTC, gabrielsanttana commented on src/services/api.php
> +
```suggestion
```

2021-01-05 22:15 UTC, wellingtonsilverio requested changes

2021-01-05 22:15 UTC, wellingtonsilverio commented on src/components/Game/index.js
> +      console.log('Recarregando');
tem um console.log aqui

2021-01-05 22:53 UTC, ticollapse commented on src/components/Game/index.js
> +      console.log('Recarregando');
Opa, pode remover isso ai

2021-01-05 23:01 UTC, wellingtonsilverio approved these changes

2021-01-05 23:10 UTC, gabrielsanttana approved these changes

2021-01-05 23:25 UTC, merged